// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl7bfadPSp3fkhKRPkx3fj_61Kbz4vrxc',
    appId: '1:458605911938:ios:31e3f5681368118d4eb99b',
    messagingSenderId: '458605911938',
    projectId: 'event-app-598ca',
    storageBucket: 'event-app-598ca.firebasestorage.app',
    iosBundleId: 'com.example.eventapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyeTV9YzC6r1XvjGQBV3uwjvP6vavjGqE',
    appId: '1:458605911938:android:aa4d10febd9d0fc04eb99b',
    messagingSenderId: '458605911938',
    projectId: 'event-app-598ca',
    storageBucket: 'event-app-598ca.firebasestorage.app',
  );

}